Add signupUser
Anna-Sergeevna/nodejs-homework-rest-api pull request #3
Opened 2022-02-01 17:42 UTC by Anna-Sergeevna

2022-02-07 11:32 UTC, Danil44 requested changes

2022-02-07 11:32 UTC, Danil44 commented on app.js
> +// const dotenv = require("dotenv");
Потрібно видалити коментарі

2022-02-07 11:33 UTC, Danil44 commented
По реалізації все чисто, але не забуваємо чистити коментарі

2022-02-10 17:40 UTC, Anna-Sergeevna commented on app.js
> +// const dotenv = require("dotenv");
@Danil44 Исправила

2022-02-11 09:51 UTC, Danil44 approved these changes

2022-02-11 09:51 UTC, merged